config/routes.rb
SurveyDanAlex::Application.routes.draw do

  resources :surveys, except: [:update, :destroy] do
    resources :questions
  end

  root :to => 'surveys#index'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
  attr_accessible :content
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  attr_accessible :content, :choices_attributes

  has_many :choices
  accepts_nested_attributes_for :choices
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :choice
  # attr_accessible :title, :body
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :content, :title, :questions_attributes
  validates :content, :presence => true
  validates :title, :presence => true, :uniqueness => true
  validate :has_at_least_one_question?

  has_many :questions
  accepts_nested_attributes_for :questions

  def has_at_least_one_question?
    errors.add(:survey_id, "does not have any questions") unless !self.questions.first.nil?
  end

  # def questions_attributes=(attributes)

  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index 
    @surveys = Survey.order('created_at DESC')
  end

  def create
    @survey = Survey.create(params[:survey])
    redirect_to root_path
  end

  def new
    @survey = Survey.new  
    3.times { @question = @survey.questions.build 
    2.times { @question.choices.build } }
  end

  def edit
  end

  def show
    @survey = Survey.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyDanAlex</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surveys/_choice_fields.html.erb
<%= f.label :content %><br>
<%= f.text_field :content, placeholder: "Choice" %><br>

app/views/surveys/_question_fields.html.erb
<%= f.label :content %><br>
<%= f.text_field :content, placeholder: "What would you like to know?" %><br>
<%= f.fields_for :choices do |builder| %>
  <%= render 'choice_fields', :f => builder %>
<% end %>

app/views/surveys/index.html.erb
<h1>Surveys!</h1>

<% @surveys.each do |survey| %>
  <h2><%= link_to survey.title, survey_path(survey) %></h2>
  <p><%= survey.content %></p>
  <hr>
<% end %> 

app/views/surveys/new.html.erb
<h1>Create a survey!</h1>

<%= form_for @survey do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: "Give me a title" %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content, placeholder: "Give me a short description for your survey", rows: 4, cols: 50  %><br>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', :f => builder %>
  <% end %>
  <%= f.submit "Hooray!" %>
<% end %>

app/views/surveys/show.html.erb
<center>
  <h2><%= @survey.title %></h2>

  <p><%= @survey.content %></p>

  <% @survey.questions.each do |question| %>
    <h3><%= question.content %></h3>
    <ul>
      <% question.choices.each do |choice| %>
        <li><%= choice.content %></li>
      <% end %>
    </ul>
  <% end %>
</center>